// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKbe6d7jXYMnU-C7CE8DgQoOT412aM-TM',
    appId: '1:654894705102:web:f3b9422d4106f5d021239f',
    messagingSenderId: '654894705102',
    projectId: 'whatsup-5182e',
    authDomain: 'whatsup-5182e.firebaseapp.com',
    storageBucket: 'whatsup-5182e.firebasestorage.app',
    measurementId: 'G-412T53G3XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2iNN89RZra1bd9zFqTsU2ZWI6D_BVbNU',
    appId: '1:654894705102:android:5a6f395a5f63036721239f',
    messagingSenderId: '654894705102',
    projectId: 'whatsup-5182e',
    storageBucket: 'whatsup-5182e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5vZcmu8PM3wh66uCkCMyMeUxk6-gVF84',
    appId: '1:654894705102:ios:5976c8a33e97456e21239f',
    messagingSenderId: '654894705102',
    projectId: 'whatsup-5182e',
    storageBucket: 'whatsup-5182e.firebasestorage.app',
    iosBundleId: 'com.example.whatsup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5vZcmu8PM3wh66uCkCMyMeUxk6-gVF84',
    appId: '1:654894705102:ios:5976c8a33e97456e21239f',
    messagingSenderId: '654894705102',
    projectId: 'whatsup-5182e',
    storageBucket: 'whatsup-5182e.firebasestorage.app',
    iosBundleId: 'com.example.whatsup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKbe6d7jXYMnU-C7CE8DgQoOT412aM-TM',
    appId: '1:654894705102:web:05fdbf5409728c8b21239f',
    messagingSenderId: '654894705102',
    projectId: 'whatsup-5182e',
    authDomain: 'whatsup-5182e.firebaseapp.com',
    storageBucket: 'whatsup-5182e.firebasestorage.app',
    measurementId: 'G-VC6E5PDRX6',
  );
}
